/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IaGp360RouteImport } from './routes/ia-gp360'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FornecedoresRouteImport } from './routes/fornecedores'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as Backups_v2RouteImport } from './routes/backups_v2'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PosEntregaIndexRouteImport } from './routes/pos-entrega.index'
import { Route as EquipeIndexRouteImport } from './routes/equipe.index'
import { Route as CentralIndexRouteImport } from './routes/central.index'
import { Route as EquipeProducaoRouteImport } from './routes/equipe.producao'
import { Route as EquipePontoRouteImport } from './routes/equipe.ponto'
import { Route as EquipePerformanceGeralRouteImport } from './routes/equipe.performance-geral'
import { Route as EquipePerformanceRouteImport } from './routes/equipe.performance'
import { Route as EquipeOnboardingRouteImport } from './routes/equipe.onboarding'
import { Route as EquipeNotificacoesRouteImport } from './routes/equipe.notificacoes'
import { Route as EquipeMetasRouteImport } from './routes/equipe.metas'
import { Route as EquipeFuncionariosRouteImport } from './routes/equipe.funcionarios'
import { Route as EquipeDashboardRouteImport } from './routes/equipe.dashboard'
import { Route as EquipeAtasRouteImport } from './routes/equipe.atas'
import { Route as EquipeAdminRouteImport } from './routes/equipe.admin'
import { Route as EquipeAdesaoRouteImport } from './routes/equipe.adesao'
import { Route as EditalIdRouteImport } from './routes/edital.$id'
import { Route as CentralIdRouteImport } from './routes/central.$id'
import { Route as BackupsV2_BASERouteImport } from './routes/backups.V2_BASE'
import { Route as BackupsLAYOUT_EXECUTIVO_BACKUPRouteImport } from './routes/backups.LAYOUT_EXECUTIVO_BACKUP'
import { Route as BackupsLAYOUT_ANTESRouteImport } from './routes/backups.LAYOUT_ANTES'
import { Route as BackupsEXECUTIVO_ANTESRouteImport } from './routes/backups.EXECUTIVO_ANTES'
import { Route as BackupsANTES_TABELA_FINALRouteImport } from './routes/backups.ANTES_TABELA_FINAL'
import { Route as BackupsANTES_MOVER_SELECIONADORouteImport } from './routes/backups.ANTES_MOVER_SELECIONADO'
import { Route as BackupsANTES_LAYOUT_EXECUTIVORouteImport } from './routes/backups.ANTES_LAYOUT_EXECUTIVO'
import { Route as EquipeAtasIndexRouteImport } from './routes/equipe.atas.index'
import { Route as EquipeAtasNovaRouteImport } from './routes/equipe.atas.nova'
import { Route as EquipeAtasIdRouteImport } from './routes/equipe.atas.$id'
import { Route as EditalIdPosEntregaRouteImport } from './routes/edital.$id.pos-entrega'
import { Route as EditalIdDisputaRouteImport } from './routes/edital.$id.disputa'
import { Route as CentralEstrategicaIdRouteImport } from './routes/central.estrategica.$id'
import { Route as ApiPublicHooksProductionAlertsRouteImport } from './routes/api.public.hooks.production-alerts'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IaGp360Route = IaGp360RouteImport.update({
  id: '/ia-gp360',
  path: '/ia-gp360',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresRoute = FornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const Backups_v2Route = Backups_v2RouteImport.update({
  id: '/backups_v2',
  path: '/backups_v2',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosEntregaIndexRoute = PosEntregaIndexRouteImport.update({
  id: '/pos-entrega/',
  path: '/pos-entrega/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralIndexRoute = CentralIndexRouteImport.update({
  id: '/central/',
  path: '/central/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeProducaoRoute = EquipeProducaoRouteImport.update({
  id: '/equipe/producao',
  path: '/equipe/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipePontoRoute = EquipePontoRouteImport.update({
  id: '/equipe/ponto',
  path: '/equipe/ponto',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipePerformanceGeralRoute = EquipePerformanceGeralRouteImport.update({
  id: '/equipe/performance-geral',
  path: '/equipe/performance-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipePerformanceRoute = EquipePerformanceRouteImport.update({
  id: '/equipe/performance',
  path: '/equipe/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeOnboardingRoute = EquipeOnboardingRouteImport.update({
  id: '/equipe/onboarding',
  path: '/equipe/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeNotificacoesRoute = EquipeNotificacoesRouteImport.update({
  id: '/equipe/notificacoes',
  path: '/equipe/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeMetasRoute = EquipeMetasRouteImport.update({
  id: '/equipe/metas',
  path: '/equipe/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeFuncionariosRoute = EquipeFuncionariosRouteImport.update({
  id: '/equipe/funcionarios',
  path: '/equipe/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeDashboardRoute = EquipeDashboardRouteImport.update({
  id: '/equipe/dashboard',
  path: '/equipe/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeAtasRoute = EquipeAtasRouteImport.update({
  id: '/equipe/atas',
  path: '/equipe/atas',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeAdminRoute = EquipeAdminRouteImport.update({
  id: '/equipe/admin',
  path: '/equipe/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeAdesaoRoute = EquipeAdesaoRouteImport.update({
  id: '/equipe/adesao',
  path: '/equipe/adesao',
  getParentRoute: () => rootRouteImport,
} as any)
const EditalIdRoute = EditalIdRouteImport.update({
  id: '/edital/$id',
  path: '/edital/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralIdRoute = CentralIdRouteImport.update({
  id: '/central/$id',
  path: '/central/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsV2_BASERoute = BackupsV2_BASERouteImport.update({
  id: '/V2_BASE',
  path: '/V2_BASE',
  getParentRoute: () => BackupsRoute,
} as any)
const BackupsLAYOUT_EXECUTIVO_BACKUPRoute =
  BackupsLAYOUT_EXECUTIVO_BACKUPRouteImport.update({
    id: '/LAYOUT_EXECUTIVO_BACKUP',
    path: '/LAYOUT_EXECUTIVO_BACKUP',
    getParentRoute: () => BackupsRoute,
  } as any)
const BackupsLAYOUT_ANTESRoute = BackupsLAYOUT_ANTESRouteImport.update({
  id: '/LAYOUT_ANTES',
  path: '/LAYOUT_ANTES',
  getParentRoute: () => BackupsRoute,
} as any)
const BackupsEXECUTIVO_ANTESRoute = BackupsEXECUTIVO_ANTESRouteImport.update({
  id: '/EXECUTIVO_ANTES',
  path: '/EXECUTIVO_ANTES',
  getParentRoute: () => BackupsRoute,
} as any)
const BackupsANTES_TABELA_FINALRoute =
  BackupsANTES_TABELA_FINALRouteImport.update({
    id: '/ANTES_TABELA_FINAL',
    path: '/ANTES_TABELA_FINAL',
    getParentRoute: () => BackupsRoute,
  } as any)
const BackupsANTES_MOVER_SELECIONADORoute =
  BackupsANTES_MOVER_SELECIONADORouteImport.update({
    id: '/ANTES_MOVER_SELECIONADO',
    path: '/ANTES_MOVER_SELECIONADO',
    getParentRoute: () => BackupsRoute,
  } as any)
const BackupsANTES_LAYOUT_EXECUTIVORoute =
  BackupsANTES_LAYOUT_EXECUTIVORouteImport.update({
    id: '/ANTES_LAYOUT_EXECUTIVO',
    path: '/ANTES_LAYOUT_EXECUTIVO',
    getParentRoute: () => BackupsRoute,
  } as any)
const EquipeAtasIndexRoute = EquipeAtasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EquipeAtasRoute,
} as any)
const EquipeAtasNovaRoute = EquipeAtasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => EquipeAtasRoute,
} as any)
const EquipeAtasIdRoute = EquipeAtasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EquipeAtasRoute,
} as any)
const EditalIdPosEntregaRoute = EditalIdPosEntregaRouteImport.update({
  id: '/pos-entrega',
  path: '/pos-entrega',
  getParentRoute: () => EditalIdRoute,
} as any)
const EditalIdDisputaRoute = EditalIdDisputaRouteImport.update({
  id: '/disputa',
  path: '/disputa',
  getParentRoute: () => EditalIdRoute,
} as any)
const CentralEstrategicaIdRoute = CentralEstrategicaIdRouteImport.update({
  id: '/central/estrategica/$id',
  path: '/central/estrategica/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProductionAlertsRoute =
  ApiPublicHooksProductionAlertsRouteImport.update({
    id: '/api/public/hooks/production-alerts',
    path: '/api/public/hooks/production-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/backups': typeof BackupsRouteWithChildren
  '/backups_v2': typeof Backups_v2Route
  '/configuracoes': typeof ConfiguracoesRoute
  '/fornecedores': typeof FornecedoresRoute
  '/historico': typeof HistoricoRoute
  '/ia-gp360': typeof IaGp360Route
  '/login': typeof LoginRoute
  '/novo': typeof NovoRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/usuarios': typeof UsuariosRoute
  '/backups/ANTES_LAYOUT_EXECUTIVO': typeof BackupsANTES_LAYOUT_EXECUTIVORoute
  '/backups/ANTES_MOVER_SELECIONADO': typeof BackupsANTES_MOVER_SELECIONADORoute
  '/backups/ANTES_TABELA_FINAL': typeof BackupsANTES_TABELA_FINALRoute
  '/backups/EXECUTIVO_ANTES': typeof BackupsEXECUTIVO_ANTESRoute
  '/backups/LAYOUT_ANTES': typeof BackupsLAYOUT_ANTESRoute
  '/backups/LAYOUT_EXECUTIVO_BACKUP': typeof BackupsLAYOUT_EXECUTIVO_BACKUPRoute
  '/backups/V2_BASE': typeof BackupsV2_BASERoute
  '/central/$id': typeof CentralIdRoute
  '/edital/$id': typeof EditalIdRouteWithChildren
  '/equipe/adesao': typeof EquipeAdesaoRoute
  '/equipe/admin': typeof EquipeAdminRoute
  '/equipe/atas': typeof EquipeAtasRouteWithChildren
  '/equipe/dashboard': typeof EquipeDashboardRoute
  '/equipe/funcionarios': typeof EquipeFuncionariosRoute
  '/equipe/metas': typeof EquipeMetasRoute
  '/equipe/notificacoes': typeof EquipeNotificacoesRoute
  '/equipe/onboarding': typeof EquipeOnboardingRoute
  '/equipe/performance': typeof EquipePerformanceRoute
  '/equipe/performance-geral': typeof EquipePerformanceGeralRoute
  '/equipe/ponto': typeof EquipePontoRoute
  '/equipe/producao': typeof EquipeProducaoRoute
  '/central/': typeof CentralIndexRoute
  '/equipe/': typeof EquipeIndexRoute
  '/pos-entrega/': typeof PosEntregaIndexRoute
  '/central/estrategica/$id': typeof CentralEstrategicaIdRoute
  '/edital/$id/disputa': typeof EditalIdDisputaRoute
  '/edital/$id/pos-entrega': typeof EditalIdPosEntregaRoute
  '/equipe/atas/$id': typeof EquipeAtasIdRoute
  '/equipe/atas/nova': typeof EquipeAtasNovaRoute
  '/equipe/atas/': typeof EquipeAtasIndexRoute
  '/api/public/hooks/production-alerts': typeof ApiPublicHooksProductionAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/backups': typeof BackupsRouteWithChildren
  '/backups_v2': typeof Backups_v2Route
  '/configuracoes': typeof ConfiguracoesRoute
  '/fornecedores': typeof FornecedoresRoute
  '/historico': typeof HistoricoRoute
  '/ia-gp360': typeof IaGp360Route
  '/login': typeof LoginRoute
  '/novo': typeof NovoRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/usuarios': typeof UsuariosRoute
  '/backups/ANTES_LAYOUT_EXECUTIVO': typeof BackupsANTES_LAYOUT_EXECUTIVORoute
  '/backups/ANTES_MOVER_SELECIONADO': typeof BackupsANTES_MOVER_SELECIONADORoute
  '/backups/ANTES_TABELA_FINAL': typeof BackupsANTES_TABELA_FINALRoute
  '/backups/EXECUTIVO_ANTES': typeof BackupsEXECUTIVO_ANTESRoute
  '/backups/LAYOUT_ANTES': typeof BackupsLAYOUT_ANTESRoute
  '/backups/LAYOUT_EXECUTIVO_BACKUP': typeof BackupsLAYOUT_EXECUTIVO_BACKUPRoute
  '/backups/V2_BASE': typeof BackupsV2_BASERoute
  '/central/$id': typeof CentralIdRoute
  '/edital/$id': typeof EditalIdRouteWithChildren
  '/equipe/adesao': typeof EquipeAdesaoRoute
  '/equipe/admin': typeof EquipeAdminRoute
  '/equipe/dashboard': typeof EquipeDashboardRoute
  '/equipe/funcionarios': typeof EquipeFuncionariosRoute
  '/equipe/metas': typeof EquipeMetasRoute
  '/equipe/notificacoes': typeof EquipeNotificacoesRoute
  '/equipe/onboarding': typeof EquipeOnboardingRoute
  '/equipe/performance': typeof EquipePerformanceRoute
  '/equipe/performance-geral': typeof EquipePerformanceGeralRoute
  '/equipe/ponto': typeof EquipePontoRoute
  '/equipe/producao': typeof EquipeProducaoRoute
  '/central': typeof CentralIndexRoute
  '/equipe': typeof EquipeIndexRoute
  '/pos-entrega': typeof PosEntregaIndexRoute
  '/central/estrategica/$id': typeof CentralEstrategicaIdRoute
  '/edital/$id/disputa': typeof EditalIdDisputaRoute
  '/edital/$id/pos-entrega': typeof EditalIdPosEntregaRoute
  '/equipe/atas/$id': typeof EquipeAtasIdRoute
  '/equipe/atas/nova': typeof EquipeAtasNovaRoute
  '/equipe/atas': typeof EquipeAtasIndexRoute
  '/api/public/hooks/production-alerts': typeof ApiPublicHooksProductionAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/backups': typeof BackupsRouteWithChildren
  '/backups_v2': typeof Backups_v2Route
  '/configuracoes': typeof ConfiguracoesRoute
  '/fornecedores': typeof FornecedoresRoute
  '/historico': typeof HistoricoRoute
  '/ia-gp360': typeof IaGp360Route
  '/login': typeof LoginRoute
  '/novo': typeof NovoRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/usuarios': typeof UsuariosRoute
  '/backups/ANTES_LAYOUT_EXECUTIVO': typeof BackupsANTES_LAYOUT_EXECUTIVORoute
  '/backups/ANTES_MOVER_SELECIONADO': typeof BackupsANTES_MOVER_SELECIONADORoute
  '/backups/ANTES_TABELA_FINAL': typeof BackupsANTES_TABELA_FINALRoute
  '/backups/EXECUTIVO_ANTES': typeof BackupsEXECUTIVO_ANTESRoute
  '/backups/LAYOUT_ANTES': typeof BackupsLAYOUT_ANTESRoute
  '/backups/LAYOUT_EXECUTIVO_BACKUP': typeof BackupsLAYOUT_EXECUTIVO_BACKUPRoute
  '/backups/V2_BASE': typeof BackupsV2_BASERoute
  '/central/$id': typeof CentralIdRoute
  '/edital/$id': typeof EditalIdRouteWithChildren
  '/equipe/adesao': typeof EquipeAdesaoRoute
  '/equipe/admin': typeof EquipeAdminRoute
  '/equipe/atas': typeof EquipeAtasRouteWithChildren
  '/equipe/dashboard': typeof EquipeDashboardRoute
  '/equipe/funcionarios': typeof EquipeFuncionariosRoute
  '/equipe/metas': typeof EquipeMetasRoute
  '/equipe/notificacoes': typeof EquipeNotificacoesRoute
  '/equipe/onboarding': typeof EquipeOnboardingRoute
  '/equipe/performance': typeof EquipePerformanceRoute
  '/equipe/performance-geral': typeof EquipePerformanceGeralRoute
  '/equipe/ponto': typeof EquipePontoRoute
  '/equipe/producao': typeof EquipeProducaoRoute
  '/central/': typeof CentralIndexRoute
  '/equipe/': typeof EquipeIndexRoute
  '/pos-entrega/': typeof PosEntregaIndexRoute
  '/central/estrategica/$id': typeof CentralEstrategicaIdRoute
  '/edital/$id/disputa': typeof EditalIdDisputaRoute
  '/edital/$id/pos-entrega': typeof EditalIdPosEntregaRoute
  '/equipe/atas/$id': typeof EquipeAtasIdRoute
  '/equipe/atas/nova': typeof EquipeAtasNovaRoute
  '/equipe/atas/': typeof EquipeAtasIndexRoute
  '/api/public/hooks/production-alerts': typeof ApiPublicHooksProductionAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/backups'
    | '/backups_v2'
    | '/configuracoes'
    | '/fornecedores'
    | '/historico'
    | '/ia-gp360'
    | '/login'
    | '/novo'
    | '/trocar-senha'
    | '/usuarios'
    | '/backups/ANTES_LAYOUT_EXECUTIVO'
    | '/backups/ANTES_MOVER_SELECIONADO'
    | '/backups/ANTES_TABELA_FINAL'
    | '/backups/EXECUTIVO_ANTES'
    | '/backups/LAYOUT_ANTES'
    | '/backups/LAYOUT_EXECUTIVO_BACKUP'
    | '/backups/V2_BASE'
    | '/central/$id'
    | '/edital/$id'
    | '/equipe/adesao'
    | '/equipe/admin'
    | '/equipe/atas'
    | '/equipe/dashboard'
    | '/equipe/funcionarios'
    | '/equipe/metas'
    | '/equipe/notificacoes'
    | '/equipe/onboarding'
    | '/equipe/performance'
    | '/equipe/performance-geral'
    | '/equipe/ponto'
    | '/equipe/producao'
    | '/central/'
    | '/equipe/'
    | '/pos-entrega/'
    | '/central/estrategica/$id'
    | '/edital/$id/disputa'
    | '/edital/$id/pos-entrega'
    | '/equipe/atas/$id'
    | '/equipe/atas/nova'
    | '/equipe/atas/'
    | '/api/public/hooks/production-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/backups'
    | '/backups_v2'
    | '/configuracoes'
    | '/fornecedores'
    | '/historico'
    | '/ia-gp360'
    | '/login'
    | '/novo'
    | '/trocar-senha'
    | '/usuarios'
    | '/backups/ANTES_LAYOUT_EXECUTIVO'
    | '/backups/ANTES_MOVER_SELECIONADO'
    | '/backups/ANTES_TABELA_FINAL'
    | '/backups/EXECUTIVO_ANTES'
    | '/backups/LAYOUT_ANTES'
    | '/backups/LAYOUT_EXECUTIVO_BACKUP'
    | '/backups/V2_BASE'
    | '/central/$id'
    | '/edital/$id'
    | '/equipe/adesao'
    | '/equipe/admin'
    | '/equipe/dashboard'
    | '/equipe/funcionarios'
    | '/equipe/metas'
    | '/equipe/notificacoes'
    | '/equipe/onboarding'
    | '/equipe/performance'
    | '/equipe/performance-geral'
    | '/equipe/ponto'
    | '/equipe/producao'
    | '/central'
    | '/equipe'
    | '/pos-entrega'
    | '/central/estrategica/$id'
    | '/edital/$id/disputa'
    | '/edital/$id/pos-entrega'
    | '/equipe/atas/$id'
    | '/equipe/atas/nova'
    | '/equipe/atas'
    | '/api/public/hooks/production-alerts'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/backups'
    | '/backups_v2'
    | '/configuracoes'
    | '/fornecedores'
    | '/historico'
    | '/ia-gp360'
    | '/login'
    | '/novo'
    | '/trocar-senha'
    | '/usuarios'
    | '/backups/ANTES_LAYOUT_EXECUTIVO'
    | '/backups/ANTES_MOVER_SELECIONADO'
    | '/backups/ANTES_TABELA_FINAL'
    | '/backups/EXECUTIVO_ANTES'
    | '/backups/LAYOUT_ANTES'
    | '/backups/LAYOUT_EXECUTIVO_BACKUP'
    | '/backups/V2_BASE'
    | '/central/$id'
    | '/edital/$id'
    | '/equipe/adesao'
    | '/equipe/admin'
    | '/equipe/atas'
    | '/equipe/dashboard'
    | '/equipe/funcionarios'
    | '/equipe/metas'
    | '/equipe/notificacoes'
    | '/equipe/onboarding'
    | '/equipe/performance'
    | '/equipe/performance-geral'
    | '/equipe/ponto'
    | '/equipe/producao'
    | '/central/'
    | '/equipe/'
    | '/pos-entrega/'
    | '/central/estrategica/$id'
    | '/edital/$id/disputa'
    | '/edital/$id/pos-entrega'
    | '/equipe/atas/$id'
    | '/equipe/atas/nova'
    | '/equipe/atas/'
    | '/api/public/hooks/production-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  BackupsRoute: typeof BackupsRouteWithChildren
  Backups_v2Route: typeof Backups_v2Route
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FornecedoresRoute: typeof FornecedoresRoute
  HistoricoRoute: typeof HistoricoRoute
  IaGp360Route: typeof IaGp360Route
  LoginRoute: typeof LoginRoute
  NovoRoute: typeof NovoRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  UsuariosRoute: typeof UsuariosRoute
  CentralIdRoute: typeof CentralIdRoute
  EditalIdRoute: typeof EditalIdRouteWithChildren
  EquipeAdesaoRoute: typeof EquipeAdesaoRoute
  EquipeAdminRoute: typeof EquipeAdminRoute
  EquipeAtasRoute: typeof EquipeAtasRouteWithChildren
  EquipeDashboardRoute: typeof EquipeDashboardRoute
  EquipeFuncionariosRoute: typeof EquipeFuncionariosRoute
  EquipeMetasRoute: typeof EquipeMetasRoute
  EquipeNotificacoesRoute: typeof EquipeNotificacoesRoute
  EquipeOnboardingRoute: typeof EquipeOnboardingRoute
  EquipePerformanceRoute: typeof EquipePerformanceRoute
  EquipePerformanceGeralRoute: typeof EquipePerformanceGeralRoute
  EquipePontoRoute: typeof EquipePontoRoute
  EquipeProducaoRoute: typeof EquipeProducaoRoute
  CentralIndexRoute: typeof CentralIndexRoute
  EquipeIndexRoute: typeof EquipeIndexRoute
  PosEntregaIndexRoute: typeof PosEntregaIndexRoute
  CentralEstrategicaIdRoute: typeof CentralEstrategicaIdRoute
  ApiPublicHooksProductionAlertsRoute: typeof ApiPublicHooksProductionAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-gp360': {
      id: '/ia-gp360'
      path: '/ia-gp360'
      fullPath: '/ia-gp360'
      preLoaderRoute: typeof IaGp360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores': {
      id: '/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof FornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups_v2': {
      id: '/backups_v2'
      path: '/backups_v2'
      fullPath: '/backups_v2'
      preLoaderRoute: typeof Backups_v2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-entrega/': {
      id: '/pos-entrega/'
      path: '/pos-entrega'
      fullPath: '/pos-entrega/'
      preLoaderRoute: typeof PosEntregaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/equipe'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central/': {
      id: '/central/'
      path: '/central'
      fullPath: '/central/'
      preLoaderRoute: typeof CentralIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/producao': {
      id: '/equipe/producao'
      path: '/equipe/producao'
      fullPath: '/equipe/producao'
      preLoaderRoute: typeof EquipeProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/ponto': {
      id: '/equipe/ponto'
      path: '/equipe/ponto'
      fullPath: '/equipe/ponto'
      preLoaderRoute: typeof EquipePontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/performance-geral': {
      id: '/equipe/performance-geral'
      path: '/equipe/performance-geral'
      fullPath: '/equipe/performance-geral'
      preLoaderRoute: typeof EquipePerformanceGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/performance': {
      id: '/equipe/performance'
      path: '/equipe/performance'
      fullPath: '/equipe/performance'
      preLoaderRoute: typeof EquipePerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/onboarding': {
      id: '/equipe/onboarding'
      path: '/equipe/onboarding'
      fullPath: '/equipe/onboarding'
      preLoaderRoute: typeof EquipeOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/notificacoes': {
      id: '/equipe/notificacoes'
      path: '/equipe/notificacoes'
      fullPath: '/equipe/notificacoes'
      preLoaderRoute: typeof EquipeNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/metas': {
      id: '/equipe/metas'
      path: '/equipe/metas'
      fullPath: '/equipe/metas'
      preLoaderRoute: typeof EquipeMetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/funcionarios': {
      id: '/equipe/funcionarios'
      path: '/equipe/funcionarios'
      fullPath: '/equipe/funcionarios'
      preLoaderRoute: typeof EquipeFuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/dashboard': {
      id: '/equipe/dashboard'
      path: '/equipe/dashboard'
      fullPath: '/equipe/dashboard'
      preLoaderRoute: typeof EquipeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/atas': {
      id: '/equipe/atas'
      path: '/equipe/atas'
      fullPath: '/equipe/atas'
      preLoaderRoute: typeof EquipeAtasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/admin': {
      id: '/equipe/admin'
      path: '/equipe/admin'
      fullPath: '/equipe/admin'
      preLoaderRoute: typeof EquipeAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/adesao': {
      id: '/equipe/adesao'
      path: '/equipe/adesao'
      fullPath: '/equipe/adesao'
      preLoaderRoute: typeof EquipeAdesaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edital/$id': {
      id: '/edital/$id'
      path: '/edital/$id'
      fullPath: '/edital/$id'
      preLoaderRoute: typeof EditalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central/$id': {
      id: '/central/$id'
      path: '/central/$id'
      fullPath: '/central/$id'
      preLoaderRoute: typeof CentralIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups/V2_BASE': {
      id: '/backups/V2_BASE'
      path: '/V2_BASE'
      fullPath: '/backups/V2_BASE'
      preLoaderRoute: typeof BackupsV2_BASERouteImport
      parentRoute: typeof BackupsRoute
    }
    '/backups/LAYOUT_EXECUTIVO_BACKUP': {
      id: '/backups/LAYOUT_EXECUTIVO_BACKUP'
      path: '/LAYOUT_EXECUTIVO_BACKUP'
      fullPath: '/backups/LAYOUT_EXECUTIVO_BACKUP'
      preLoaderRoute: typeof BackupsLAYOUT_EXECUTIVO_BACKUPRouteImport
      parentRoute: typeof BackupsRoute
    }
    '/backups/LAYOUT_ANTES': {
      id: '/backups/LAYOUT_ANTES'
      path: '/LAYOUT_ANTES'
      fullPath: '/backups/LAYOUT_ANTES'
      preLoaderRoute: typeof BackupsLAYOUT_ANTESRouteImport
      parentRoute: typeof BackupsRoute
    }
    '/backups/EXECUTIVO_ANTES': {
      id: '/backups/EXECUTIVO_ANTES'
      path: '/EXECUTIVO_ANTES'
      fullPath: '/backups/EXECUTIVO_ANTES'
      preLoaderRoute: typeof BackupsEXECUTIVO_ANTESRouteImport
      parentRoute: typeof BackupsRoute
    }
    '/backups/ANTES_TABELA_FINAL': {
      id: '/backups/ANTES_TABELA_FINAL'
      path: '/ANTES_TABELA_FINAL'
      fullPath: '/backups/ANTES_TABELA_FINAL'
      preLoaderRoute: typeof BackupsANTES_TABELA_FINALRouteImport
      parentRoute: typeof BackupsRoute
    }
    '/backups/ANTES_MOVER_SELECIONADO': {
      id: '/backups/ANTES_MOVER_SELECIONADO'
      path: '/ANTES_MOVER_SELECIONADO'
      fullPath: '/backups/ANTES_MOVER_SELECIONADO'
      preLoaderRoute: typeof BackupsANTES_MOVER_SELECIONADORouteImport
      parentRoute: typeof BackupsRoute
    }
    '/backups/ANTES_LAYOUT_EXECUTIVO': {
      id: '/backups/ANTES_LAYOUT_EXECUTIVO'
      path: '/ANTES_LAYOUT_EXECUTIVO'
      fullPath: '/backups/ANTES_LAYOUT_EXECUTIVO'
      preLoaderRoute: typeof BackupsANTES_LAYOUT_EXECUTIVORouteImport
      parentRoute: typeof BackupsRoute
    }
    '/equipe/atas/': {
      id: '/equipe/atas/'
      path: '/'
      fullPath: '/equipe/atas/'
      preLoaderRoute: typeof EquipeAtasIndexRouteImport
      parentRoute: typeof EquipeAtasRoute
    }
    '/equipe/atas/nova': {
      id: '/equipe/atas/nova'
      path: '/nova'
      fullPath: '/equipe/atas/nova'
      preLoaderRoute: typeof EquipeAtasNovaRouteImport
      parentRoute: typeof EquipeAtasRoute
    }
    '/equipe/atas/$id': {
      id: '/equipe/atas/$id'
      path: '/$id'
      fullPath: '/equipe/atas/$id'
      preLoaderRoute: typeof EquipeAtasIdRouteImport
      parentRoute: typeof EquipeAtasRoute
    }
    '/edital/$id/pos-entrega': {
      id: '/edital/$id/pos-entrega'
      path: '/pos-entrega'
      fullPath: '/edital/$id/pos-entrega'
      preLoaderRoute: typeof EditalIdPosEntregaRouteImport
      parentRoute: typeof EditalIdRoute
    }
    '/edital/$id/disputa': {
      id: '/edital/$id/disputa'
      path: '/disputa'
      fullPath: '/edital/$id/disputa'
      preLoaderRoute: typeof EditalIdDisputaRouteImport
      parentRoute: typeof EditalIdRoute
    }
    '/central/estrategica/$id': {
      id: '/central/estrategica/$id'
      path: '/central/estrategica/$id'
      fullPath: '/central/estrategica/$id'
      preLoaderRoute: typeof CentralEstrategicaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/production-alerts': {
      id: '/api/public/hooks/production-alerts'
      path: '/api/public/hooks/production-alerts'
      fullPath: '/api/public/hooks/production-alerts'
      preLoaderRoute: typeof ApiPublicHooksProductionAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BackupsRouteChildren {
  BackupsANTES_LAYOUT_EXECUTIVORoute: typeof BackupsANTES_LAYOUT_EXECUTIVORoute
  BackupsANTES_MOVER_SELECIONADORoute: typeof BackupsANTES_MOVER_SELECIONADORoute
  BackupsANTES_TABELA_FINALRoute: typeof BackupsANTES_TABELA_FINALRoute
  BackupsEXECUTIVO_ANTESRoute: typeof BackupsEXECUTIVO_ANTESRoute
  BackupsLAYOUT_ANTESRoute: typeof BackupsLAYOUT_ANTESRoute
  BackupsLAYOUT_EXECUTIVO_BACKUPRoute: typeof BackupsLAYOUT_EXECUTIVO_BACKUPRoute
  BackupsV2_BASERoute: typeof BackupsV2_BASERoute
}

const BackupsRouteChildren: BackupsRouteChildren = {
  BackupsANTES_LAYOUT_EXECUTIVORoute: BackupsANTES_LAYOUT_EXECUTIVORoute,
  BackupsANTES_MOVER_SELECIONADORoute: BackupsANTES_MOVER_SELECIONADORoute,
  BackupsANTES_TABELA_FINALRoute: BackupsANTES_TABELA_FINALRoute,
  BackupsEXECUTIVO_ANTESRoute: BackupsEXECUTIVO_ANTESRoute,
  BackupsLAYOUT_ANTESRoute: BackupsLAYOUT_ANTESRoute,
  BackupsLAYOUT_EXECUTIVO_BACKUPRoute: BackupsLAYOUT_EXECUTIVO_BACKUPRoute,
  BackupsV2_BASERoute: BackupsV2_BASERoute,
}

const BackupsRouteWithChildren =
  BackupsRoute._addFileChildren(BackupsRouteChildren)

interface EditalIdRouteChildren {
  EditalIdDisputaRoute: typeof EditalIdDisputaRoute
  EditalIdPosEntregaRoute: typeof EditalIdPosEntregaRoute
}

const EditalIdRouteChildren: EditalIdRouteChildren = {
  EditalIdDisputaRoute: EditalIdDisputaRoute,
  EditalIdPosEntregaRoute: EditalIdPosEntregaRoute,
}

const EditalIdRouteWithChildren = EditalIdRoute._addFileChildren(
  EditalIdRouteChildren,
)

interface EquipeAtasRouteChildren {
  EquipeAtasIdRoute: typeof EquipeAtasIdRoute
  EquipeAtasNovaRoute: typeof EquipeAtasNovaRoute
  EquipeAtasIndexRoute: typeof EquipeAtasIndexRoute
}

const EquipeAtasRouteChildren: EquipeAtasRouteChildren = {
  EquipeAtasIdRoute: EquipeAtasIdRoute,
  EquipeAtasNovaRoute: EquipeAtasNovaRoute,
  EquipeAtasIndexRoute: EquipeAtasIndexRoute,
}

const EquipeAtasRouteWithChildren = EquipeAtasRoute._addFileChildren(
  EquipeAtasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  BackupsRoute: BackupsRouteWithChildren,
  Backups_v2Route: Backups_v2Route,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FornecedoresRoute: FornecedoresRoute,
  HistoricoRoute: HistoricoRoute,
  IaGp360Route: IaGp360Route,
  LoginRoute: LoginRoute,
  NovoRoute: NovoRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  UsuariosRoute: UsuariosRoute,
  CentralIdRoute: CentralIdRoute,
  EditalIdRoute: EditalIdRouteWithChildren,
  EquipeAdesaoRoute: EquipeAdesaoRoute,
  EquipeAdminRoute: EquipeAdminRoute,
  EquipeAtasRoute: EquipeAtasRouteWithChildren,
  EquipeDashboardRoute: EquipeDashboardRoute,
  EquipeFuncionariosRoute: EquipeFuncionariosRoute,
  EquipeMetasRoute: EquipeMetasRoute,
  EquipeNotificacoesRoute: EquipeNotificacoesRoute,
  EquipeOnboardingRoute: EquipeOnboardingRoute,
  EquipePerformanceRoute: EquipePerformanceRoute,
  EquipePerformanceGeralRoute: EquipePerformanceGeralRoute,
  EquipePontoRoute: EquipePontoRoute,
  EquipeProducaoRoute: EquipeProducaoRoute,
  CentralIndexRoute: CentralIndexRoute,
  EquipeIndexRoute: EquipeIndexRoute,
  PosEntregaIndexRoute: PosEntregaIndexRoute,
  CentralEstrategicaIdRoute: CentralEstrategicaIdRoute,
  ApiPublicHooksProductionAlertsRoute: ApiPublicHooksProductionAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
