ALTER TABLE public.bids 
ADD COLUMN IF NOT EXISTS secretaria TEXT,
ADD COLUMN IF NOT EXISTS tipo_disputa TEXT,
ADD COLUMN IF NOT EXISTS criterio_julgamento TEXT,
ADD COLUMN IF NOT EXISTS portal_disputa TEXT,
ADD COLUMN IF NOT EXISTS cidade_uf TEXT,
ADD COLUMN IF NOT EXISTS contato_responsavel TEXT,
ADD COLUMN IF NOT EXISTS telefone_contato TEXT,
ADD COLUMN IF NOT EXISTS email_contato TEXT,
ADD COLUMN IF NOT EXISTS valor_total_estimado NUMERIC DEFAULT 0;

ALTER TABLE public.bid_items
ADD COLUMN IF NOT EXISTS valor_estimado_total NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS valor_maximo NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS lote TEXT,
ADD COLUMN IF NOT EXISTS me_epp BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS catmat TEXT;